export const ManagerFinalRedefData = {
  // ================================
  // AGILE
  // ================================
  Agile: {
    phases: ["Develop", "Test", "Deploy", "Review"],
    taskTypes: {
      Develop: ["Documentation", "System Development", "Discussion & Review"],
      Test: ["Documentation", "System Development", "Discussion & Review"],
      Deploy: ["Documentation", "System Development", "Discussion & Review"],
      Review: ["Documentation", "System Development", "Discussion & Review"],
    },
    tasks: {
      Documentation: [
        "Re-Polishing: Chapter 1",
        "3.Re-Polishing: Chapter 2",
        "8.Re-Polishing: Chapter 3",
        "4. Re-Polishing: Chapter 4",
        "14.Re-Polishing: Development",
        "6.Re-Polishing:Verification and Testing",
        "5.Re-Polishing: Implementation Plan",
        "6.Re-Polishing:Installation Process",
        "7.Re-Polishing: Chapter 5",
        "8.Re-Polishing Supporting Sections",
        "5. Review Documentation and & System Details",
        "6. Re-Defense: Manuscript Submission",
 
      ],
      "System Development": [
        "10.UI Enhancement",
        "11.Functionality Enhancement",
        "12.Bug Fixing",
        "13.Re-Defense System QA",
        "19.Bug Fixing and Final Adjustments",
        "20.Patch Update",
        "21.Review Users Feedback",
        "22.Final Re-Defense",
        "23.Final Re-Defense Feedback Integration",
        "4.Manuscript Re-Submission for AI and Plagiarism Check",
 
      ],
      "Discussion & Review": [
        "5.Capstone Meeting",
        "6.Adviser Consultation",
        "7.Meeting with the User/Client",
        "8.Gather Users/Client Feedback",
        "9.Final Adjustment of the System",
        "Final Re-Defense Preparation",
      ],
    },
    subtasks: {
      "Re-Polishing: Chapter 1": ["7.Introduction", "8.Objectives", "9.Scope and Limitation"],
      "3.Re-Polishing: Chapter 2": ["6.Related Theories", "7.Related Literature"],
      "8.Re-Polishing: Chapter 3": ["7.Implementation", "8.Development"],
      "4. Re-Polishing: Chapter 4": ["10.Methodology", "11.Environment", "12.Requirement Specification", "13.Design"],
      "14.Re-Polishing: Development": [
        "7.Software",
        "8.Hardware Specification",
        "9.Program Specification",
        "10.Programming Enviroment",
        "11.Development Diagram",
        "12.Test Plan",],
        "6.Re-Polishing:Verification and Testing": ["5.Unit Testing", "6.Integration Testing", "7.System Testing", "8.Acceptance Testing"],
        "5.Re-Polishing: Implementation Plan": ["6.Physical Environment", "7.Interfaces", "8.Functionality", "9.Data", "10.Security"],
        "7.Re-Polishing: Chapter 5": ["4.Conclusion", "5.Recomendations", "7.Appendices"],
        "8.Re-Polishing Supporting Sections": ["4.References", "Resource Person", "6.Appendices"],
        "13.Re-Defense System QA": [
        "1.Unit Testing",
        "15.Compatibility Testing",
        "16.Performance Testing",
        "17.Stress Testing",
        "18.Load Testing",
        "14.Concurrent Testing",
        "15.Pacing Time",
        "16.Response Time",
        "17.Network Testing",
      ],
        "Final Re-Defense Preparation": [
        "System Testing Request Letter",
        "4.PowerPoint Presentation",
        "5.Mock Defense",
        "6.Manuscript Printing",
      ], 
 
    },
    elements: {
      "7.Introduction": ["Project Context", "Background of the Study", "Policies and Procedures", "Users Position"],
      "8.Objectives": ["General Objectives", "Specific Objectives"],
      "9.Scope and Limitation": ["Scope", "Limitation"],
      "7.Implementation": ["Hardware", "Software", "Peopleware"],
      "8.Development": ["Hardware", "Software", "Peopleware"],
      "11.Environment": ["Locale", "Population of the Study", "Organizational Chart/Profile"],
      "12.Requirement Specification": [
        "Operational Feasibility [Fishbone Diagram]",
        "Operational Feasibility [Functional Decomposition Diagram]",
        "Technical Feasibility",
        "Schedule Feasibility",
        "Economic Feasibility",
        "Requirements Modeling [Context Diagram]",
        "Requirements Modeling [Data Flow Diagram]",
        "Requirements Modeling [System Flowchart]",
        "Requirements Modeling [Program Flowchart]",
        "Requirements Modeling [Use Case Diagram]",
        "Requirements Modeling [Use Class Diagram]",
        "Requirements Modeling [Sequence  Diagram]",
        "Requirements Modeling [Activity Diagram]",
        "Risk Assessment/Analysis",
      ],
      "13.Design": [
        "Output and User-interface Design Forms",
        "Data Design",
        "System Architecture [Network Model]",
        "System Architecture [Network Topology]",
        "System Architecture [Network Security]",
      ],
      "10.Programming Enviroment": ["Front End", "Back End", "Programming Considerations and Issues"],
      "12.Test Plan": ["Test Data"],
      "6.Integration Testing": ["Compatibility Testing", "Performance Testing", "Stress Testing", "Load Testing"],
      "7.System Testing": ["System Function", "Test Data", "Test Result and Observations"],
      "6.Appendices": ["Appendix F", "Appendix G", "Appendix H", "Appendix I"],
      "7.Appendices": ["Appendix A", "Appendix B", "Appendix C", "Appendix D", "Appendix E"],
 
    },
  },
 
  // ================================
  // EXTREME PROGRAMMING (XP)
  // ================================
  "Extreme Programming": {
    phases: ["Coding", "Testing", "Listening"],
    taskTypes: {
      Coding: ["Documentation", "System Development", "Discussion & Review"],
      Testing: ["Documentation", "System Development", "Discussion & Review"],
      Listening: ["Documentation", "System Development", "Discussion & Review"],
    },
    tasks: {
      Documentation: [
        "Re-Polishing: Chapter 1",
        "3.Re-Polishing: Chapter 2",
        "8.Re-Polishing: Chapter 3",
        "4. Re-Polishing: Chapter 4",
        "14.Re-Polishing: Development",
        "6.Re-Polishing:Verification and Testing",
        "5.Re-Polishing: Implementation Plan",
        "6.Re-Polishing:Installation Process",
        "7.Re-Polishing: Chapter 5",
        "8.Re-Polishing Supporting Sections",
        "5. Review Documentation and & System Details",
        "6. Re-Defense: Manuscript Submission",
 
      ],
      "System Development": [
        "13.Iterative UI Refinement",
        "14.Continuous Feature Improvement",
        "15.Ongoing Refactoring and Defect Resolution ",
        "16.Re-Defense System QA",
        "19.Bug Fixing and Final Adjustments",
        "20.Patch Update",
        "21.Review Users Feedback",
        "22.Final Re-Defense",
        "23.Final Re-Defense Feedback Integration",
        "4.Manuscript Re-Submission for AI and Plagiarism Check",
 
      ],
      "Discussion & Review": [
        "5.Capstone Meeting",
        "6.Adviser Consultation",
        "7.Meeting with the User/Client", 
        "Final Re-Defense Preparation",
      ],
    },
    subtasks: {
      "Re-Polishing: Chapter 1": ["7.Introduction", "8.Objectives", "9.Scope and Limitation"],
      "3.Re-Polishing: Chapter 2": ["6.Related Theories", "7.Related Literature"],
      "8.Re-Polishing: Chapter 3": ["20.Implementation", "21.Development"],
      "4. Re-Polishing: Chapter 4": ["10.Methodology", "11.Environment", "12.Requirement Specification", "13.Design"],
      "14.Re-Polishing: Development": [
        "7.Software",
        "8.Hardware Specification",
        "9.Program Specification",
        "10.Programming Enviroment",
        "11.Development Diagram",
        "12.Test Plan",],
        "6.Re-Polishing:Verification and Testing": ["5.Unit Testing", "6.Integration Testing", "7.System Testing", "8.Acceptance Testing"],
        "5.Re-Polishing: Implementation Plan": ["6.Physical Environment", "7.Interfaces", "8.Functionality", "9.Data", "10.Security"],
        "7.Re-Polishing: Chapter 5": ["4.Conclusion", "5.Recomendations", "6.Appendices"],
        "8.Re-Polishing Supporting Sections": ["4.References", "Resource Person", "7.Appendices"],
        "16.Re-Defense System QA": [
        "1.Unit Testing",
        "15.Compatibility Testing",
        "16.Performance Testing",
        "17.Stress Testing",
        "18.Load Testing",
        "17.Concurrent Testing",
        "18.Pacing Time",
        "19.Response Time",
        "20.Network Testing",
      ],
        "Final Re-Defense Preparation": [
        "System Testing Request Letter",
        "4.PowerPoint Presentation",
        "5.Mock Defense",
        "6.Manuscript Printing",
      ], 
 
    },
    elements: {
      "7.Introduction": ["Project Context", "Background of the Study", "Policies and Procedures", "Users Position"],
      "8.Objectives": ["General Objectives", "Specific Objectives"],
      "9.Scope and Limitation": ["Scope", "Limitation"],
      "20.Implementation": ["Hardware", "Software", "Peopleware"],
      "21.Development": ["Hardware", "Software", "Peopleware"],
      "11.Environment": ["Locale", "Population of the Study", "Organizational Chart/Profile"],
      "12.Requirement Specification": [
        "Operational Feasibility [Fishbone Diagram]",
        "Operational Feasibility [Functional Decomposition Diagram]",
        "Technical Feasibility",
        "Schedule Feasibility",
        "Economic Feasibility",
        "Requirements Modeling [Context Diagram]",
        "Requirements Modeling [Data Flow Diagram]",
        "Requirements Modeling [System Flowchart]",
        "Requirements Modeling [Program Flowchart]",
        "Requirements Modeling [Use Case Diagram]",
        "Requirements Modeling [Use Class Diagram]",
        "Requirements Modeling [Sequence  Diagram]",
        "Requirements Modeling [Activity Diagram]",
        "Risk Assessment/Analysis",
      ],
      "13.Design": [
        "Output and User-interface Design Forms",
        "Data Design",
        "System Architecture [Network Model]",
        "System Architecture [Network Topology]",
        "System Architecture [Network Security]",
      ],
      "10.Programming Enviroment": ["Front End", "Back End", "Programming Considerations and Issues"],
      "12.Test Plan": ["Test Data"],
      "6.Integration Testing": ["Compatibility Testing", "Performance Testing", "Stress Testing", "Load Testing"],
      "7.System Testing": ["System Function", "Test Data", "Test Result and Observations"],
      "6.Appendices": ["Appendix F", "Appendix G", "Appendix H", "Appendix I"],
      "7.Appendices": ["Appendix A", "Appendix B", "Appendix C", "Appendix D", "Appendix E"],
 
    },
  },
 
  // ================================
  // SPIRAL
  // ================================
  Spiral: {
    phases: ["Engineering", "Evaluation"],
    taskTypes: {
      Engineering: ["Documentation", "System Development", "Discussion & Review"],
      Evaluation: ["Documentation", "System Development", "Discussion & Review"],
    },
    tasks: {
      Documentation: [
        "Re-Polishing: Chapter 1",
        "3.Re-Polishing: Chapter 2",
        "8.Re-Polishing: Chapter 3",
        "4. Re-Polishing: Chapter 4",
        "14.Re-Polishing: Development",
        "6.Re-Polishing:Verification and Testing",
        "5.Re-Polishing: Implementation Plan",
        "6.Re-Polishing:Installation Process",
        "7.Re-Polishing: Chapter 5",
        "8.Re-Polishing Supporting Sections",
        "5. Review Documentation and & System Details",
        "6. Re-Defense: Manuscript Submission",
 
      ],
      "System Development": [
        "Refine User Interface Based on Feedback",
        "Feature Improvement Implementation",
        "System Issue Resolution",
        "16.Re-Defense System QA",
        "19.Bug Fixing and Final Adjustments",
        "20.Patch Update",
        "21.Review Users Feedback",
        "22.Final Re-Defense",
        "23.Final Re-Defense Feedback Integration",
        "4.Manuscript Re-Submission for AI and Plagiarism Check",
 
      ],
      "Discussion & Review": [
        "5.Capstone Meeting",
        "6.Adviser Consultation",
        "7.Meeting with the User/Client", 
        "Final Re-Defense Preparation",
      ],
    },
    subtasks: {
      "Re-Polishing: Chapter 1": ["7.Introduction", "8.Objectives", "9.Scope and Limitation"],
      "3.Re-Polishing: Chapter 2": ["6.Related Theories", "7.Related Literature"],
      "8.Re-Polishing: Chapter 3": ["20.Implementation", "21.Development"],
      "4. Re-Polishing: Chapter 4": ["10.Methodology", "11.Environment", "12.Requirement Specification", "13.Design"],
      "14.Re-Polishing: Development": [
        "7.Software",
        "8.Hardware Specification",
        "9.Program Specification",
        "10.Programming Enviroment",
        "11.Development Diagram",
        "12.Test Plan",],
        "6.Re-Polishing:Verification and Testing": ["5.Unit Testing", "6.Integration Testing", "7.System Testing", "8.Acceptance Testing"],
        "5.Re-Polishing: Implementation Plan": ["6.Physical Environment", "7.Interfaces", "8.Functionality", "9.Data", "10.Security"],
        "7.Re-Polishing: Chapter 5": ["4.Conclusion", "5.Recomendations", "6.Appendices"],
        "8.Re-Polishing Supporting Sections": ["4.References", "Resource Person", "7.Appendices"],
        "16.Re-Defense System QA": [
        "1.Unit Testing",
        "15.Compatibility Testing",
        "16.Performance Testing",
        "17.Stress Testing",
        "18.Load Testing",
        "17.Concurrent Testing",
        "18.Pacing Time",
        "19.Response Time",
        "20.Network Testing",
      ],
        "Final Re-Defense Preparation": [
        "System Testing Request Letter",
        "4.PowerPoint Presentation",
        "5.Mock Defense",
        "6.Manuscript Printing",
      ], 
 
    },
    elements: {
      "7.Introduction": ["Project Context", "Background of the Study", "Policies and Procedures", "Users Position"],
      "8.Objectives": ["General Objectives", "Specific Objectives"],
      "9.Scope and Limitation": ["Scope", "Limitation"],
      "20.Implementation": ["Hardware", "Software", "Peopleware"],
      "21.Development": ["Hardware", "Software", "Peopleware"],
      "11.Environment": ["Locale", "Population of the Study", "Organizational Chart/Profile"],
      "12.Requirement Specification": [
        "Operational Feasibility [Fishbone Diagram]",
        "Operational Feasibility [Functional Decomposition Diagram]",
        "Technical Feasibility",
        "Schedule Feasibility",
        "Economic Feasibility",
        "Requirements Modeling [Context Diagram]",
        "Requirements Modeling [Data Flow Diagram]",
        "Requirements Modeling [System Flowchart]",
        "Requirements Modeling [Program Flowchart]",
        "Requirements Modeling [Use Case Diagram]",
        "Requirements Modeling [Use Class Diagram]",
        "Requirements Modeling [Sequence  Diagram]",
        "Requirements Modeling [Activity Diagram]",
        "Risk Assessment/Analysis",
      ],
      "13.Design": [
        "Output and User-interface Design Forms",
        "Data Design",
        "System Architecture [Network Model]",
        "System Architecture [Network Topology]",
        "System Architecture [Network Security]",
      ],
      "10.Programming Enviroment": ["Front End", "Back End", "Programming Considerations and Issues"],
      "12.Test Plan": ["Test Data"],
      "6.Integration Testing": ["Compatibility Testing", "Performance Testing", "Stress Testing", "Load Testing"],
      "7.System Testing": ["System Function", "Test Data", "Test Result and Observations"],
      "6.Appendices": ["Appendix F", "Appendix G", "Appendix H", "Appendix I"],
      "7.Appendices": ["Appendix A", "Appendix B", "Appendix C", "Appendix D", "Appendix E"],
 
    },
  },
 
  // ================================
  // RAD
  // ================================
   RAD: {
    phases: ["Construction", "Cutover"],
    taskTypes: {
      Engineering: ["Documentation", "System Development", "Discussion & Review"],
      Evaluation: ["Documentation", "System Development", "Discussion & Review"],
    },
     tasks: {
      Documentation: [
        "Re-Polishing: Chapter 1",
        "3.Re-Polishing: Chapter 2",
        "8.Re-Polishing: Chapter 3",
        "4. Re-Polishing: Chapter 4",
        "14.Re-Polishing: Development",
        "6.Re-Polishing:Verification and Testing",
        "5.Re-Polishing: Implementation Plan",
        "6.Re-Polishing:Installation Process",
        "7.Re-Polishing: Chapter 5",
        "8.Re-Polishing Supporting Sections",
        "5. Review Documentation and & System Details",
        "6. Re-Defense: Manuscript Submission",
 
      ],
      "System Development": [
        "11.UI Enhancement",
        "12.Functionality Enhancement",
        "13.Bug Fixing",
        "16.Re-Defense System QA",
        "19.Bug Fixing and Final Adjustments",
        "20.Patch Update",
        "22.System Update Orientation for End Users",
        "23.Review Users Feedback",
        "24.System Completion and Cutover Activities",
        "25.Final Re-Defense",
        "26.Final Re-Defense Feedback Integration",
        "4.Manuscript Re-Submission for AI and Plagiarism Check",
 
      ],
      "Discussion & Review": [
        "5.Capstone Meeting",
        "6.Adviser Consultation",
        "7.Meeting with the User/Client", 
        "Final Re-Defense Preparation",
      ],
    },
    subtasks: {
      "Re-Polishing: Chapter 1": ["7.Introduction", "8.Objectives", "9.Scope and Limitation"],
      "3.Re-Polishing: Chapter 2": ["6.Related Theories", "7.Related Literature"],
      "8.Re-Polishing: Chapter 3": ["20.Implementation", "21.Development"],
      "4. Re-Polishing: Chapter 4": ["10.Methodology", "11.Environment", "12.Requirement Specification", "13.Design"],
      "14.Re-Polishing: Development": [
        "7.Software",
        "8.Hardware Specification",
        "9.Program Specification",
        "10.Programming Enviroment",
        "11.Development Diagram",
        "12.Test Plan",],
        "6.Re-Polishing:Verification and Testing": ["5.Unit Testing", "6.Integration Testing", "7.System Testing", "8.Acceptance Testing"],
        "5.Re-Polishing: Implementation Plan": ["6.Physical Environment", "7.Interfaces", "8.Functionality", "9.Data", "10.Security"],
        "7.Re-Polishing: Chapter 5": ["4.Conclusion", "5.Recomendations", "6.Appendices"],
        "8.Re-Polishing Supporting Sections": ["4.References", "Resource Person", "7.Appendices"],
        "16.Re-Defense System QA": [
        "1.Unit Testing",
        "15.Compatibility Testing",
        "16.Performance Testing",
        "17.Stress Testing",
        "18.Load Testing",
        "17.Concurrent Testing",
        "18.Pacing Time",
        "19.Response Time",
        "20.Network Testing",
      ],
        "Final Re-Defense Preparation": [
        "System Testing Request Letter",
        "4.PowerPoint Presentation",
        "5.Mock Defense",
        "6.Manuscript Printing",
      ], 
 
    },
    elements: {
      "7.Introduction": ["Project Context", "Background of the Study", "Policies and Procedures", "Users Position"],
      "8.Objectives": ["General Objectives", "Specific Objectives"],
      "9.Scope and Limitation": ["Scope", "Limitation"],
      "20.Implementation": ["Hardware", "Software", "Peopleware"],
      "21.Development": ["Hardware", "Software", "Peopleware"],
      "11.Environment": ["Locale", "Population of the Study", "Organizational Chart/Profile"],
      "12.Requirement Specification": [
        "Operational Feasibility [Fishbone Diagram]",
        "Operational Feasibility [Functional Decomposition Diagram]",
        "Technical Feasibility",
        "Schedule Feasibility",
        "Economic Feasibility",
        "Requirements Modeling [Context Diagram]",
        "Requirements Modeling [Data Flow Diagram]",
        "Requirements Modeling [System Flowchart]",
        "Requirements Modeling [Program Flowchart]",
        "Requirements Modeling [Use Case Diagram]",
        "Requirements Modeling [Use Class Diagram]",
        "Requirements Modeling [Sequence  Diagram]",
        "Requirements Modeling [Activity Diagram]",
        "Risk Assessment/Analysis",
      ],
      "13.Design": [
        "Output and User-interface Design Forms",
        "Data Design",
        "System Architecture [Network Model]",
        "System Architecture [Network Topology]",
        "System Architecture [Network Security]",
      ],
      "10.Programming Enviroment": ["Front End", "Back End", "Programming Considerations and Issues"],
      "12.Test Plan": ["Test Data"],
      "6.Integration Testing": ["Compatibility Testing", "Performance Testing", "Stress Testing", "Load Testing"],
      "7.System Testing": ["System Function", "Test Data", "Test Result and Observations"],
      "6.Appendices": ["Appendix F", "Appendix G", "Appendix H", "Appendix I"],
      "7.Appendices": ["Appendix A", "Appendix B", "Appendix C", "Appendix D", "Appendix E"],
 
    },
  },
 
 
  // ================================
  // PROTOTYPING
  // ================================
  Prototyping: {
  phases: ["Refining Prototype", "Implement Product & Maintain"],
  taskTypes: {
    "Refining Prototype": ["Documentation", "System Development", "Discussion & Review"],
    "Implement Product & Maintain": ["Documentation", "System Development", "Discussion & Review"],
    "Discussion & Review": ["Documentation", "System Development", "Discussion & Review"],
  },
 tasks: {
      Documentation: [
        "Final Defense Response: UI Polishing & Functional Optimization",
        "Re-Polishing: Chapter 1",
        "3.Re-Polishing: Chapter 2",
        "8.Re-Polishing: Chapter 3",
        "4. Re-Polishing: Chapter 4",
        "14.Re-Polishing: Development",
        "6.Re-Polishing:Verification and Testing",
        "5.Re-Polishing: Implementation Plan",
        "6.Re-Polishing:Installation Process",
        "7.Re-Polishing: Chapter 5",
        "8.Re-Polishing Supporting Sections",
        "5. Review Documentation and & System Details",
        "6. Re-Defense: Manuscript Submission",
 
      ],
      "System Development": [
        "11.Improved visual design and layout",
        "12.Feature & Workflow Improvements",
        "13.Bug Fixing",
        "16.Re-Defense System QA",
        "19.Bug Fixing and Final Adjustments",
        "19.System Patch",
        "20.Review Users Feedback",
        "21.Finalization of the System",
        "22.Final Re-Defense",
        "23.Final Re-Defense Feedback Integration",
        "4.Manuscript Re-Submission for AI and Plagiarism Check",
 
      ],
      "Discussion & Review": [
        "5.Capstone Meeting",
        "6.Adviser Consultation",
        "7.Meeting with the User/Client", 
        "Final Re-Defense Preparation",
      ],
    },
    subtasks: {
      "Re-Polishing: Chapter 1": ["7.Introduction", "8.Objectives", "9.Scope and Limitation"],
      "3.Re-Polishing: Chapter 2": ["6.Related Theories", "7.Related Literature"],
      "8.Re-Polishing: Chapter 3": ["20.Implementation", "21.Development"],
      "4. Re-Polishing: Chapter 4": ["10.Methodology", "11.Environment", "12.Requirement Specification", "13.Design"],
      "14.Re-Polishing: Development": [
        "7.Software",
        "8.Hardware Specification",
        "9.Program Specification",
        "10.Programming Enviroment",
        "11.Development Diagram",
        "12.Test Plan",],
        "6.Re-Polishing:Verification and Testing": ["5.Unit Testing", "6.Integration Testing", "7.System Testing", "8.Acceptance Testing"],
        "5.Re-Polishing: Implementation Plan": ["6.Physical Environment", "7.Interfaces", "8.Functionality", "9.Data", "10.Security"],
        "7.Re-Polishing: Chapter 5": ["4.Conclusion", "5.Recomendations", "6.Appendices"],
        "8.Re-Polishing Supporting Sections": ["4.References", "Resource Person", "7.Appendices"],
        "16.Re-Defense System QA": [
        "1.Unit Testing",
        "15.Compatibility Testing",
        "16.Performance Testing",
        "17.Stress Testing",
        "18.Load Testing",
        "17.Concurrent Testing",
        "18.Pacing Time",
        "19.Response Time",
        "20.Network Testing",
      ],
        "Final Re-Defense Preparation": [
        "System Testing Request Letter",
        "4.PowerPoint Presentation",
        "5.Mock Defense",
        "6.Manuscript Printing",
      ], 
 
    },
    elements: {
      "7.Introduction": ["Project Context", "Background of the Study", "Policies and Procedures", "Users Position"],
      "8.Objectives": ["General Objectives", "Specific Objectives"],
      "9.Scope and Limitation": ["Scope", "Limitation"],
      "20.Implementation": ["Hardware", "Software", "Peopleware"],
      "21.Development": ["Hardware", "Software", "Peopleware"],
      "11.Environment": ["Locale", "Population of the Study", "Organizational Chart/Profile"],
      "12.Requirement Specification": [
        "Operational Feasibility [Fishbone Diagram]",
        "Operational Feasibility [Functional Decomposition Diagram]",
        "Technical Feasibility",
        "Schedule Feasibility",
        "Economic Feasibility",
        "Requirements Modeling [Context Diagram]",
        "Requirements Modeling [Data Flow Diagram]",
        "Requirements Modeling [System Flowchart]",
        "Requirements Modeling [Program Flowchart]",
        "Requirements Modeling [Use Case Diagram]",
        "Requirements Modeling [Use Class Diagram]",
        "Requirements Modeling [Sequence  Diagram]",
        "Requirements Modeling [Activity Diagram]",
        "Risk Assessment/Analysis",
      ],
      "13.Design": [
        "Output and User-interface Design Forms",
        "Data Design",
        "System Architecture [Network Model]",
        "System Architecture [Network Topology]",
        "System Architecture [Network Security]",
      ],
      "10.Programming Enviroment": ["Front End", "Back End", "Programming Considerations and Issues"],
      "12.Test Plan": ["Test Data"],
      "6.Integration Testing": ["Compatibility Testing", "Performance Testing", "Stress Testing", "Load Testing"],
      "7.System Testing": ["System Function", "Test Data", "Test Result and Observations"],
      "6.Appendices": ["Appendix F", "Appendix G", "Appendix H", "Appendix I"],
      "7.Appendices": ["Appendix A", "Appendix B", "Appendix C", "Appendix D", "Appendix E"],
 
    },
},
};